import Header from './components/Header'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="m-auto min-h-screen max-w-7xl bg-keppel bg-gradient-to-b from-silver-sand to-transparent to-[200%]  text-black dark:bg-gradient-to-b dark:from-black dark:to-keppel dark:to-[500%]">
        <Header />
        {children}
      </body>
    </html>
  )
}
